### ISSUE TITLE
TypeError: cellRendererFunc is not a function

### ISSUE THREAD

**Issue by shivekundefined** [ceolter/ag-grid#883]
Getting TypeError: cellRendererFunc is not a function from the ag-gridd enterprice version 4.1.3 and version 4.1.4 as well..

![ag-grid-issuw_v_4 1 3](https://cloud.githubusercontent.com/assets/17401303/15036753/19b7def4-12b1-11e6-82f1-1af4a4ee9d7d.png)

For more: I am getting this error when I am using cellRenderer && renderer: 'group', while using grouping of rows. It was working fine in version 4.0.7. But after upgrading the GRID.JS file i am getting this error.

**Comment by ceolter** [comment]
https://www.ag-grid.com/change-log/changeLogIndex.php

```If you are using the built in groupCellRenderer, check the examples on how to configure it. The colDef.cellRenderer property is broken up into cellRenderer and cellRendererParams.```
