### ISSUE TITLE
Missing dependencies from ag-charts-types

### ISSUE THREAD

**Issue by Vic-M** [ceolter/ag-grid#9603]
Hello, when trying to build an angular application using version 33.0.3, I get the following error:
```
[user@server app]$ ng serve
...
Error: node_modules/ag-grid-angular/lib/ag-grid-angular.component.d.ts:2:58 - error TS2307: Cannot find module 'ag-charts-types' or its corresponding type declarations.

2 import type { AgChartTheme, AgChartThemeOverrides } from 'ag-charts-types';

Error: node_modules/ag-grid-enterprise/dist/types/src/allEnterpriseModule.d.ts:1:39 - error TS2307: Cannot find module 'ag-charts-types' or its corresponding type declarations.

1 import type { IntegratedModule } from 'ag-charts-types';

Error: node_modules/ag-grid-enterprise/dist/types/src/charts/integratedChartsModule.d.ts:1:39 - error TS2307: Cannot find module 'ag-charts-types' or its corresponding type declarations.

1 import type { IntegratedModule } from 'ag-charts-types';

Error: node_modules/ag-grid-enterprise/dist/types/src/sparkline/sparklinesModule.d.ts:1:39 - error TS2307: Cannot find module 'ag-charts-types' or its corresponding type declarations.

1 import type { IntegratedModule } from 'ag-charts-types';
```

In my package.json, I have 
```
        "ag-grid-angular": "^33.0.3",
        "ag-grid-community": "^33.0.3",
        "ag-grid-enterprise": "^33.0.3",
```

Am I missing a required package?

**Comment by AG-Zoheil** [comment]
Hi @Vic-M,

We've made some changes to modules to significantly improve bundle size in the grid. Please view the following pages regarding your question:

https://www.ag-grid.com/angular-data-grid/modules/
https://www.ag-grid.com/angular-data-grid/upgrading-to-ag-grid-33/

Kind regards,
Zoheil

**Comment by Vic-M** [comment]
Turns out I had to delete my node_modules/ and package-lock.json and run `npm i` again.

**Comment by Sebi11** [comment]
There seems to be a problem indeed with version 33.0.3.
I tried to remove my node_modules and package-lock.json, withous success, I still get this error:

> ✘ [ERROR] TS2307: Cannot find module 'ag-charts-types' or its corresponding type declarations. [plugin angular-compiler]
> 
>     node_modules/ag-grid-angular/lib/ag-grid-angular.component.d.ts:2:57:
>       2 │ ...ype { AgChartTheme, AgChartThemeOverrides } from 'ag-charts-types';
>         ╵                                                     ~~~~~~~~~~~~~~~~~

I installed the versions 33.0.0, 33.0.1 and 33.0.2 and I didn't encounter the error.

EDIT: after a last attempt, it worked with version 33.0.3 as well. I don't understand why, since I deleted by node_modules directory 🙄

**Comment by pfteter** [comment]
My understanding is that someone included a dependency in the monorepo that it shouldn't
This is porbably a AgGrid Bug.

../core/node_modules/ag-grid-community/dist/types/core/interfaces/IChartService.d.ts:1:65 - error TS2307: Cannot find module 'ag-charts-types' or its corresponding type declarations.

1 import type { AgChartThemeOverrides, AgChartThemePalette } from 'ag-charts-types';


ag-grid-community package.json is not including the  'ag-charts-types' from NPM as a package but it's using it. 
That is causing trouble to those who include ag-grid-community since that depndency is missing.

Search for the line of code:
import type { AgChartThemeOverrides, AgChartThemePalette } from 'ag-charts-types';

the bug is here:
https://github.com/ag-grid/ag-grid/blob/c84f08bbedd19fcd3e06c59b586d18536205f76c/packages/ag-grid-community/src/interfaces/IChartService.ts#L1


AgGrid should not include types from ag-charts-types, if so it should be defined as a dependency in package.json

**Comment by hire-a-dev** [comment]
I also encoutered this issue. Even in the latest version 33.0.4.  The problem seems to be these parts in node modules

- import type { IntegratedModule } from 'ag-charts-types';
and
- with: (params: IntegratedModule) => _ModuleWithApi<_GridChartsGridApi>;

I manually removed the import an changed IntegratedModule to any because i do not use the charts. The application at least is compiling.
