### ISSUE TITLE
version 4.2.x issues with onSelectionChanged and Angular1.x

### ISSUE THREAD

**Issue by iberodev** [ceolter/ag-grid#936]
I have updated from 4.1.x to 4.2.5 and I have found a few issues with Angular1.

My scenario is as follows. I have the grid and depending on the rows selected through the selectable checkbox (with `checkboxSelection: true`) columns I display or I hide some buttons outside the grid.

In my gridOptions I have `angularCompileRows: true`. I am not compiling headers or filters since I don't think it should apply and also it does not seem to make any difference.

So when creating the grid I am passing a callback `onSelectionChanged`. Something like:
```
() => {
    let selectedRows: number = this.myGridOptions.api.getSelectedRows().length;
    this.scopeVariables.multiSelect = selectedRows > 0;
    //this.myGridOptions.api.recomputeAggregates(); //this was a workaround to allow my variable to be reflected in the view when it changed
 });
```

the in my view I have something like the following, where a div is shown based on whether 1 or more rows are selected:
```
<div ng-show="myController.scopeVariables.multiSelect">one or more selected</div>
<div ag-grid="myController.myGridOptions" class="ag-blue"></div>
```

For some reason it's as if `myController.scopeVariables.multiSelect` were not properly watched in the scope and in the view its value is not updated when the callback function `onSelectChanged` is executed.
I used to fix that in the version 4.1.x with a workaround `this.myGridOptions.api.recomputeAggregates();`
and that seemed to do the trick and my boolean variable was reflected in the view.

Since I updated to 4.2.x this still works but now I cannot select multiple rows simply by clicking on each row's checkbox. As soon as I check the next checkbox, the previous row gets unselected (probably because `recomputeAggregates()` re-renders the table). That didn't happen before. However if I press CTRL I can select as many rows as I'd like because my grid is configured with `rowSelection: "multiple"` (so that's not the problem).

I thought I might get rid of the workaround and do things properly. So my question is:
**Why if I modify some scope's variable inside the `onSelectionChanged` event this change is not being reflected in my view? and why this would be reflected if I do something extra like `recomputeAggregates()`?**

PS: I also tried to use `this.myGridOptions.refreshView();` but it throws an error saying "refreshView is not a function".

Thanks

**Comment by ceolter** [comment]
you need to call the digest cycle inside your callback. it's an angular thing.
https://www.sitepoint.com/understanding-angulars-apply-digest/
try this at the end of your callback:
```
setTimtout( function() { 
  $scope.$apply(); 
}, 0}
```
